---
sudo: false
dist: focal
language: python
cache: pip

addons:
  postgresql: '12'
  apt:
      packages:
        - postgresql-12

matrix:
  include:
    # https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django
    - {env: DJANGO=3.2.13, python: '3.6'}
    - {env: DJANGO=3.2.13, python: '3.7'}
    - {env: DJANGO=3.2.13, python: '3.8'}
    - {env: DJANGO=3.2.13, python: '3.9'}
    - {env: DJANGO=3.2.13, python: '3.10'}
    - {env: DJANGO=3.2.13, python: 'nightly'}
    - {env: DJANGO=3.2.13, python: 'pypy3'}
    - {env: DJANGO=4.0.4, python: '3.9'}
    - {env: DJANGO=4.0.4, python: '3.10'}
    - {env: DJANGO=4.0.4, python: 'nightly'}

    - {env: DJANGO=master, python: '3.6'}
    - {env: DJANGO=master, python: '3.7'}
    - {env: DJANGO=master, python: '3.8'}
    - {env: DJANGO=master, python: '3.9'}
    - {env: DJANGO=master, python: '3.10'}
    - {env: DJANGO=master, python: 'nightly'}

  allow_failures:
    - python: 'nightly'
    - env: DJANGO=master

install:
    - if [[ $DJANGO == 'master' ]]; then travis_retry pip install https://github.com/django/django/archive/master.tar.gz; fi
    - if [[ $DJANGO != 'master' ]]; then travis_retry pip install django==$DJANGO; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then travis_retry pip install psycopg2cffi>=2.7; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install psycopg2-binary; fi
    - travis_retry pip install gevent
    - python setup.py -q install

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - postgres --version
  - psql -c 'create database test;' -U postgres

script:
  - python -Wall runtests.py
